
spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://localhost:3306/fleam-auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


