logging:
  level:
    tk.mybatis: debug
    com.fleam.serviceauth: debug
  #日志
  config: classpath:logback-${spring.profiles.active}.xml
#  config: classpath:logback-prod.xml

server:
  port: 8764

spring:
  profiles:
    active: @profileActive@

